#!/usr/bin/env bash

#generating authors for project after a commit message has been done  

{
	cat <<-'EOH'
	#This file lists all individuls having contributed content to the repository
	#For how it is generated, see 'generateAuthors'
	EOH
	echo
	git log --format='%aN <%aE>' | LC_ALL=C.UTF-* sort -uf
} >  AUTHORS
